CREATE TABLE IF NOT EXISTS tenants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  subdomain VARCHAR(100) NOT NULL UNIQUE,
  custom_domain VARCHAR(255) UNIQUE,
  db_name VARCHAR(255) NOT NULL UNIQUE,
  logo_url VARCHAR(500),
  primary_color VARCHAR(7) DEFAULT '#2f4274',
  expired_at DATE NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE tenants ADD COLUMN expired_at DATE NULL;
ALTER TABLE tenants ADD COLUMN is_active BOOLEAN DEFAULT true;
